controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif
view:
  CAMERA_POS: [0.1, 1.3, 2.7]
  WINDOW_DIMENSIONS: [800, 600]
  BACKGROUND_IMAGE: examples/characters/char10/background.png
scene:
  ANIMATED_CHARACTERS:
  - character_cfg: examples/characters/char9/char_cfg.yaml
    motion_cfg: examples/config/motion/zombie.yaml
    retarget_cfg: examples/config/retarget/fair1_spf.yaml
    size: [30, 300]
